name: i_am_rich
description: This is the "I am rich" app for learning flutter part 02
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    #- images/diamond.png # Add the specific image file
    - images/ # Add the entire folder
